### ISSUE TITLE
State the difference with PEZ

### ISSUE THREAD

**Issue by shudong-zhang** [joycenerd/P4D#1]
"Hard Prompts Made Easy: Gradient-Based Discrete Optimization for Prompt Tuning and Discovery"
https://github.com/YuxinWenRick/hard-prompts-made-easy/blob/main/examples/prompt_inversion_sd.ipynb

**Comment by zhiyichin** [comment]
In our paper, we state that our prompt design and optimization scheme exhibit high similarity with PEZ. However, it is worth noting that we adapt their method by incorporating the regression loss of the noise prediction from the unconstrained T2I model $G$ and the safe T2I model $G^\prime$, which significantly differs from the original PEZ. Moreover, the intentions behind our method and PEZ vary; while PEZ aims to find a prompt that can generate aesthetically pleasing target images, our method focuses on jailbreaking T2I models with safety mechanisms. Applying PEZ directly without any modification results in a very low attack success rate for our specific purpose.

**Comment by shudong-zhang** [comment]
Thank you for your response. I agree with you. The authors should emphasize the difference with PEZ in the related work, and add comparison experiment with PEZ.

I apologize for my impulsiveness in posting my opinion in a public place without communicating with the author.  And apologies for the impact on the author's reputation.

**Comment by StableInfo** [comment]
Hello both @joycenerd  and @shudong-zhang , I found this post by searching for "hard prompt made easy" because I was searching for its appliucation with Stable diffusion.
My question: is there an extension or any easy method how to use this P4D new technology with Stable diffusion or similar (ComfyUI) ? even a SIMPLE EXAMPLE how to apply it would be welcome please?
